Omert/tsk 11901 oracle cloud sp
blinkops/blink-steampipe pull request #18
Opened 2022-12-28 16:34 UTC by marakomer

2022-12-28 16:56 UTC, DanielDinsh requested changes
Env link?

Did you try to run the generic action?

I'm asking this because I think you forgot to add - 
`COPY plugins/local/oci/oci.plugin /home/steampipe/.steampipe/plugins/local/oci/oci.plugin`

2022-12-28 16:56 UTC, DanielDinsh commented on scripts/generators/oci.go
> +		return fmt.Errorf("unable to prepare gcp credentials on configuration: %w", err)
```suggestion
		return fmt.Errorf("unable to prepare oci credentials on configuration: %w", err)
```

2022-12-29 08:39 UTC, marakomer commented
env is running, I did not you're right, updated docker to include it

2022-12-29 11:21 UTC, DanielDinsh approved these changes

2022-12-29 11:26 UTC, merged