Ofir pernik/tsk 6859 Dockerfile & Credential Generators
blinkops/blink-steampipe pull request #2
Opened 2022-08-15 10:15 UTC by itsofirblink

2022-08-15 11:48 UTC, rimar-blink requested changes

2022-08-15 11:48 UTC, rimar-blink commented on Dockerfile
> +FROM turbot/steampipe
lets put a specific version

2022-08-15 11:48 UTC, rimar-blink commented on scripts/generators/kubernetes_config.go
> +type KubectlConfig struct {
think it would have been much easier to simply use json + templating, but ok :)

2022-08-15 11:48 UTC, rimar-blink commented on scripts/generators/env.go
> +func SetEnv(variable ...Variable) error {
bad name, rename to WriteEnvFile

2022-08-15 11:48 UTC, rimar-blink commented on scripts/generators/env.go
> +		envFile += fmt.Sprintf("export %s=%s", info.Key, info.Value)
Add newline

2022-08-15 11:48 UTC, rimar-blink commented on scripts/generators/aws.go
> +func (gen AWSCredentialGenerator) detect() (_, _, _ string) {
add names to return values

2022-08-15 15:43 UTC, rimar-blink submitted a review, later dismissed

2022-08-18 15:37 UTC, Idanraman submitted a review, later dismissed

2022-08-21 12:53 UTC, Idanraman approved these changes

2022-08-21 12:55 UTC, merged